#!/usr/bin/env python3
"""Bake edify.atoms preset patterns into src/presets.ts.

Run from the repo root with the project venv:
    .venv/bin/python plugins/acode-regex-builder/tools/gen_presets.py
"""

from __future__ import annotations

import json
import pathlib
import sys
from typing import Any

PLUGIN_DIR = pathlib.Path(__file__).resolve().parent.parent
OUT = PLUGIN_DIR / "src" / "presets.ts"


def main() -> int:
    from edify import atoms

    presets: list[dict[str, str]] = []
    failures: list[str] = []
    for name in sorted(atoms.__all__):
        obj: Any = getattr(atoms, name, None)
        if obj is None:
            failures.append(f"{name}: missing")
            continue
        try:
            pattern = obj.to_regex_string()
        except Exception as exc:
            failures.append(f"{name}: {type(exc).__name__}")
            continue
        presets.append({"name": name, "pattern": pattern})

    lines = [
        "// GENERATED by tools/gen_presets.py — do not edit by hand.",
        "export interface Preset {",
        "  name: string;",
        "  pattern: string;",
        "}",
        "",
        "export const PRESETS: Preset[] = [",
    ]
    lines.extend(
        f"  {{ name: {json.dumps(item['name'])}, pattern: {json.dumps(item['pattern'])} }},"
        for item in presets
    )
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(presets)} presets to {OUT}")
    if failures:
        print("skipped:", "; ".join(failures), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
